2020-09-13 21:04:24,540 ERROR: Exception on /withdraw [POST] [in /home/kr/miniconda3/envs/mybc/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/kr/miniconda3/envs/mybc/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kr/miniconda3/envs/mybc/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kr/miniconda3/envs/mybc/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kr/miniconda3/envs/mybc/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/kr/miniconda3/envs/mybc/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kr/miniconda3/envs/mybc/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kr/miniconda3/envs/mybc/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/kr/workspace/ElectronicData/app/routes.py", line 31, in wrapped
    return f(*args, **kwargs)
  File "/home/kr/workspace/ElectronicData/app/routes.py", line 424, in withdraw
    money=form.amount.data, addr=current_user.address)
TypeError: withdraw() missing 1 required positional argument: 'password'
2020-09-13 21:05:04,360 INFO: Electronic startup [in /home/kr/workspace/ElectronicData/app/__init__.py:58]
2020-09-13 21:20:11,061 INFO: Electronic startup [in /home/kr/workspace/ElectronicData/app/__init__.py:58]
2020-09-13 21:21:08,601 INFO: Electronic startup [in /home/kr/workspace/ElectronicData/app/__init__.py:58]
2020-09-13 21:24:03,317 INFO: Electronic startup [in /home/kr/workspace/ElectronicData/app/__init__.py:58]
2020-09-13 21:26:16,209 ERROR: Exception on /issue [POST] [in /home/kr/miniconda3/envs/mybc/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/kr/miniconda3/envs/mybc/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kr/miniconda3/envs/mybc/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kr/miniconda3/envs/mybc/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kr/miniconda3/envs/mybc/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/kr/miniconda3/envs/mybc/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kr/miniconda3/envs/mybc/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kr/miniconda3/envs/mybc/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/kr/workspace/ElectronicData/app/routes.py", line 120, in issue
    endTime=endTime, money=money, infoHash=infoHash, owner=current_user.address)
TypeError: createCharity() missing 1 required positional argument: 'password'
2020-09-13 21:31:38,514 INFO: Electronic startup [in /home/kr/workspace/ElectronicData/app/__init__.py:58]
2020-09-13 21:41:39,589 INFO: Electronic startup [in /home/kr/workspace/ElectronicData/app/__init__.py:58]
2020-09-13 21:41:48,004 INFO: Electronic startup [in /home/kr/workspace/ElectronicData/app/__init__.py:58]
2020-09-13 21:43:37,518 INFO: Electronic startup [in /home/kr/workspace/ElectronicData/app/__init__.py:58]
2020-09-13 21:49:03,592 INFO: Electronic startup [in /home/kr/workspace/ElectronicData/app/__init__.py:58]
2020-09-13 21:52:23,966 INFO: Electronic startup [in /home/kr/workspace/ElectronicData/app/__init__.py:58]
2020-09-13 21:58:40,474 INFO: Electronic startup [in /home/kr/workspace/ElectronicData/app/__init__.py:58]
2020-09-13 22:01:59,830 INFO: Electronic startup [in /home/kr/workspace/ElectronicData/app/__init__.py:58]
2020-09-13 22:04:37,719 INFO: Electronic startup [in /home/kr/workspace/ElectronicData/app/__init__.py:58]
2020-09-13 22:12:41,894 INFO: Electronic startup [in /home/kr/workspace/ElectronicData/app/__init__.py:58]
2020-09-13 22:14:06,402 INFO: Electronic startup [in /home/kr/workspace/ElectronicData/app/__init__.py:58]
2020-09-13 22:15:38,454 INFO: Electronic startup [in /home/kr/workspace/ElectronicData/app/__init__.py:58]
2020-09-13 22:15:40,545 ERROR: Exception on /my_res_donate [GET] [in /home/kr/miniconda3/envs/mybc/lib/python3.7/site-packages/flask/app.py:1892]
Traceback (most recent call last):
  File "/home/kr/miniconda3/envs/mybc/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/kr/miniconda3/envs/mybc/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/kr/miniconda3/envs/mybc/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kr/miniconda3/envs/mybc/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/kr/miniconda3/envs/mybc/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kr/miniconda3/envs/mybc/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/kr/miniconda3/envs/mybc/lib/python3.7/site-packages/flask_login/utils.py", line 261, in decorated_view
    return func(*args, **kwargs)
  File "/home/kr/workspace/ElectronicData/app/routes.py", line 379, in my_res_donate
    resources=result
  File "/home/kr/miniconda3/envs/mybc/lib/python3.7/site-packages/flask/templating.py", line 140, in render_template
    ctx.app,
  File "/home/kr/miniconda3/envs/mybc/lib/python3.7/site-packages/flask/templating.py", line 120, in _render
    rv = template.render(context)
  File "/home/kr/miniconda3/envs/mybc/lib/python3.7/site-packages/jinja2/asyncsupport.py", line 76, in render
    return original_render(self, *args, **kwargs)
  File "/home/kr/miniconda3/envs/mybc/lib/python3.7/site-packages/jinja2/environment.py", line 1008, in render
    return self.environment.handle_exception(exc_info, True)
  File "/home/kr/miniconda3/envs/mybc/lib/python3.7/site-packages/jinja2/environment.py", line 780, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/kr/miniconda3/envs/mybc/lib/python3.7/site-packages/jinja2/_compat.py", line 37, in reraise
    raise value.with_traceback(tb)
  File "/home/kr/workspace/ElectronicData/app/templates/myres/res_donate.html", line 1, in top-level template code
    {% extends "base/base.html" %} {% block styles %}
  File "/home/kr/miniconda3/envs/mybc/lib/python3.7/site-packages/jinja2/environment.py", line 1005, in render
    return concat(self.root_render_func(self.new_context(vars)))
  File "/home/kr/workspace/ElectronicData/app/templates/myres/res_donate.html", line 14, in root
    <div class="panel-body">
  File "/home/kr/workspace/ElectronicData/app/templates/base/base.html", line 79, in root
    "hideDuration": "1000",
  File "/home/kr/workspace/ElectronicData/app/templates/myres/res_donate.html", line 46, in block_content
    {% endfor %}
  File "/home/kr/miniconda3/envs/mybc/lib/python3.7/site-packages/jinja2/runtime.py", line 262, in call
    return __obj(*args, **kwargs)
  File "/home/kr/miniconda3/envs/mybc/lib/python3.7/site-packages/jinja2/runtime.py", line 630, in _fail_with_undefined_error
    raise self._undefined_exception(hint)
jinja2.exceptions.UndefinedError: 'dict object' has no attribute 'avatar'
2020-09-13 22:20:13,713 INFO: Electronic startup [in /home/kr/workspace/ElectronicData/app/__init__.py:58]
